config/routes.rb
AccountManager::Application.routes.draw do
  resources :incomes

  resources :expenses

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :cost, :frequency, :name

  def dailycost
    cost / frequency
  end

  def self.totalExpense
    Expense.sum("cost / frequency")
  end

end

app/models/income.rb
class Income < ActiveRecord::Base
  attr_accessible :amount, :frequency, :name

  def dailyIncome
    amount / frequency
  end

  def self.totalIncome
    Income.sum("amount / frequency")
  end

  def self.projectForward
    if Income.count == 0 or Expense.count == 0
      return 0
    end
    numberOfDays = (Date.today..Date.parse('2013-12-26')).count
    totalInDays = Income.sum("amount / frequency") * numberOfDays

    #totalin = totalInDays * numberOfDays

   totalExDays = Expense.where("frequency > ?",0).sum("cost / frequency") * numberOfDays
   totalOnceExDays = Expense.where("frequency <= ?",0).sum("cost")
   if totalOnceExDays.nil?
     puts blah
   end


    puts totalInDays
    puts totalExDays
    totalInDays - totalExDays - totalOnceExDays
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(params[:expense])

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
    @expense = Expense.find(params[:id])

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @incomes }
    end
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
    @income = Income.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @income }
    end
  end

  # GET /incomes/new
  # GET /incomes/new.json
  def new
    @income = Income.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @income }
    end
  end

  # GET /incomes/1/edit
  def edit
    @income = Income.find(params[:id])
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(params[:income])

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render json: @income, status: :created, location: @income }
      else
        format.html { render action: "new" }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /incomes/1
  # PUT /incomes/1.json
  def update
    @income = Income.find(params[:id])

    respond_to do |format|
      if @income.update_attributes(params[:income])
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income = Income.find(params[:id])
    @income.destroy

    respond_to do |format|
      format.html { redirect_to incomes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/expenses/_form.html.slim
= form_for @expense do |f|
  - if @expense.errors.any?
    #error_explanation
      h2 = "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
      ul
        - @expense.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :cost
    = f.text_field :cost
  .field
    = f.label :frequency
    = f.select(:frequency, [['Daily', "1"],['Weekly', "7"],['Fortnightly',"14"],['Monthly', "30"],['Quarterly', "90"],['6 Monthly',"180"],['Yearly',"365"],['Once Off',"0"]])
  .field
  .actions = f.submit 'Save'

app/views/expenses/edit.html.slim
h1 Editing expense

== render 'form'

= link_to 'Show', @expense
'|
= link_to 'Back', expense_path

app/views/expenses/index.html.slim
h1 Listing Expenses


table
  tr
    th Name
    th Amount
    th Frequency
    th
    th
    th

  - @expenses.each do |expense|
    tr
      td = expense.name
      td = expense.cost
      td = expense.frequency
      td = link_to 'Show', expense
      td = link_to 'Edit', edit_expense_path(expense)
      td = link_to 'Destroy', expense, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New expense', new_expense_path

app/views/expenses/new.html.slim
h1 New Expense

== render 'form'

= link_to 'Back', expenses_path

app/views/expenses/show.html.slim
p#notice = notice

p
  strong Name:
  = @expense.name
p
  strong Amount:
  = @expense.cost
p
  strong Frequency:
  = @expense.frequency

= link_to 'Edit', edit_expense_path(@expense)
'|
= link_to 'Back', expenses_path

app/views/incomes/_form.html.slim
= form_for @income do |f|
  - if @income.errors.any?
    #error_explanation
      h2 = "#{pluralize(@income.errors.count, "error")} prohibited this income from being saved:"
      ul
        - @income.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :frequency
    = f.select(:frequency, [['Daily', "1"],['Weekly', "7"],['Fortnightly',"14"],['Monthly', "30"],['Quarterly', "90"],['6 Monthly',"180"],['Yearly',"365"]])

  .actions = f.submit 'Save'

app/views/incomes/_modal.html.slim
/! Modal
#myModal.modal.hide.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-header
    button.close aria-hidden="true" data-dismiss="modal" type="button" x
    h3#myModalLabel Modal header
  .modal-body
    p Test of modal
    div class="progress progress-danger progress-striped active"
      div class="bar" style="width: 20%;"
  .modal-footer
    button.btn aria-hidden="true" data-dismiss="modal" Close
    button.btn.btn-primary Save changes

app/views/incomes/edit.html.slim
h1 Editing income

== render 'form'

= link_to 'Show', @income
'|
= link_to 'Back', incomes_path

app/views/incomes/index.html.slim
h1 Listing incomes

table
  tr
    th Name
    th Amount
    th Frequency
    th
    th
    th

  - @incomes.each do |income|
    tr
      td = income.name
      td = income.amount
      td = income.frequency
      td = link_to 'Show', income
      td = link_to 'Edit', edit_income_path(income)
      td = link_to 'Destroy', income, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Income', new_income_path

app/views/incomes/new.html.slim
h1 New income

== render 'form'

= link_to 'Back', incomes_path

app/views/incomes/show.html.slim
p#notice = notice

p
  strong Name:
  = @income.name
p
  strong Amount:
  = @income.amount
p
  strong Frequency:
  = @income.frequency

= link_to 'Edit', edit_income_path(@income)
'|
= link_to 'Back', incomes_path

app/views/layouts/_nav.html.slim
div class="navbar navbar-fixed-top"
  div class="navbar-inner"
    div class="container"
      a class="brand" Account Manager
      ul class="nav"
        li = link_to 'Expenses', 'expenses'
        li = link_to 'Income', 'incomes'

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Compass Twitter Bootstrap Demo
    meta name="keywords" content="template language"

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tag


  body
    = render 'layouts/nav'
    div class="container"
      div class="content"
        div class="hero-unit"
          h3 Amount Saved by 26 December 2013
          h4 = "$#{Income.projectForward.ceil}"
      == yield